services:
    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: woom
            MYSQL_USER: admin
            MYSQL_PASSWORD: somepassword

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "8000:80"
        volumes:
            - ./wp-content/plugins/random-products:/var/www/html/wp-content/plugins/random-products
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: admin
            WORDPRESS_DB_PASSWORD: somepassword
            WORDPRESS_DB_NAME: woom

volumes:
    db_data: {}
